User/Redactor roles managment
lodz-university-of-technology-masi/Yellow pull request #4
Opened 2019-05-11 12:36 UTC by hXl3s

2019-05-11 19:00 UTC, Drutol requested changes

2019-05-11 19:00 UTC, Drutol commented on backend/src/main/java/edu/pl/masi/yellow/controller/api/v1/manage/Redactors.java
> +                "moderator"))
`"moderator"` shouldn't be an enum? Or some `const` at least?

2019-05-11 19:00 UTC, Drutol commented on backend/src/main/java/edu/pl/masi/yellow/entity/UserEntity.java
> +    @JsonProperty("user_role")
Could we adopt camelCase naming convention? I have a feeling it will be messy in js.

2019-05-11 19:00 UTC, Drutol commented on backend/src/main/java/edu/pl/masi/yellow/manager/UserManager.java
> +            response = new GenericResponse("User with name "
Is there no string interpolation?

2019-05-11 19:00 UTC, Drutol commented on backend/src/main/java/edu/pl/masi/yellow/repository/UserRepository.java
>      @Query("SELECT u FROM UserEntity u WHERE u.username = :username")
Damn, raw SQL... really?

2019-05-12 09:48 UTC, hXl3s commented on backend/src/main/java/edu/pl/masi/yellow/manager/UserManager.java
> +            response = new GenericResponse("User with name "
No really clear way, just Java things, I will leave additions, they are simpler

2019-05-12 09:48 UTC, hXl3s commented on backend/src/main/java/edu/pl/masi/yellow/repository/UserRepository.java
>      @Query("SELECT u FROM UserEntity u WHERE u.username = :username")
Not so raw as you see, but you can tell spring how to construct query, so why not to do it?

2019-05-12 10:47 UTC, Drutol commented on backend/src/main/java/edu/pl/masi/yellow/repository/UserRepository.java
>      @Query("SELECT u FROM UserEntity u WHERE u.username = :username")
Still looks very suspicious... /shrug

2019-05-12 12:42 UTC, Posiadacz07 approved these changes

2019-05-12 19:48 UTC, merged